config/routes.rb
Fms::Application.routes.draw do

  root :to => "fragrances#index"
  resource :session, :only => [:new, :create, :destroy]

  resources :fragrances, :except => [:destroy] do
    resources :formulation_versions, :except => [:destroy], :path => 'versions', :shallow => true do
      put 'publish', :on => :member
    end
  end

  resources :accords, :except => [:destroy] do
    member do
      put :publish
    end
    resources :formulation_versions, :except => [:destroy], :path => 'versions'
    collection do
      get 'autocomplete'
    end
    resources :versions, :except => [:destroy], :controller => 'formulation_versions'
  end

  resources :ingredients do
    collection do
      get 'autocomplete'
    end
    resources :ingredient_prices, :only => [:create]
  end
  resources :ingredient_price_lists, :only => [:create, :update, :index]

end

app/models/ingredient_price.rb
# coding: utf-8
class IngredientPrice < ActiveRecord::Base

  belongs_to :ingredient
  acts_as_audited :associated_with => :ingredient

  SUPPORTED_CURRENCIES = { 'INR' => 'Rs. ', 'USD' => '$', 'EUR' => '€' }

  belongs_to :priceable, :polymorphic => true
  #has_many :currencies, :class_name => 'PriceCurrency'
  scope :chronological, order(:applicable_from.asc)
  scope :net, where(:ingredient_price_list_id => nil)
  scope :gross, where(:ingredient_price_list_id.ne => nil)
  scope :applicable_from, lambda { |applicable_from = Date.today| select('distinct on (ingredient_id) *').where(:applicable_from.lte => applicable_from).order('ingredient_id, applicable_from desc') }

  validates :applicable_from, :timeliness => { :type => :date }, :uniqueness => { :scope => :ingredient_id, :message => "must be unique" }, :if => :net?
  validate :atleast_one_price

  class << self
    def current
      as_on(Date.today)
    end

    def as_on(date)
      #where(:applicable_from.lte => date.to_date).last
      applicable_from(date.to_date).first
    end
  end

  def in?(currency_code)
    self.send("#{currency_code.to_s.downcase}").present?
  end

  def amount(currency_code)
    self.send("#{currency_code.to_s.downcase}")
  end

  def in(currency_code)
    self.send currency_code.to_s.downcase
  end

  def to(currency_code)
    if in?(currency_code)
      return amount(currency_code)
    else
      target_currency_rate = Currency.find_by_code!(currency_code).prices.as_on(applicable_from).amount
      SUPPORTED_CURRENCIES.keys.each do |supported_currency|
        if in?(supported_currency)
          supported_currency_rate = Currency.find_by_code!(supported_currency).prices.as_on(applicable_from).amount
          return amount(supported_currency) * supported_currency_rate / target_currency_rate
        end
      end
    end
  end


  def net?
    ingredient_price_list_id.nil?
  end

  def gross?
    ingredient_price_list_id.present?
  end

  private

  def atleast_one_price
    unless inr || usd || eur
      errors.add(:base, "At least one price should be entered")
    end
  end
end

app/controllers/ingredient_prices_controller.rb
class IngredientPricesController < ApplicationController
  before_filter :find_ingredient

  def create
    @price = @ingredient.prices.build params[:ingredient_price]
    if @price.save
      flash[:success] = "Added prices for '#{@price.applicable_from.to_s(:long)}'"
    end
  end

  private

  def find_ingredient
    @ingredient = Ingredient.find params[:ingredient_id]
  end
end

app/helpers/ingredient_prices_helper.rb
module IngredientPricesHelper
end

app/views/ingredient_prices/_form.html.haml
= form_for [@ingredient, @price ||= IngredientPrice.new()], :remote => true do |form|
  = form.error_messages
  %fieldset 
    %ol.form
      %li
        = form.label :applicable_from
        = form.text_field :applicable_from, :class => 'date'
        = reqd
      %li.inline
        = form.label :prices
        %ol
          %li
            = form.label :inr, "INR"
            = form.text_field :inr, :class => 'numeric'
          %li
            = form.label :usd, "USD"
            = form.text_field :usd, :class => 'numeric'
          %li
            = form.label :eur, "EUR"
            = form.text_field :eur, :class => 'numeric'
      %li
        = form.label :audit_comment, "Comment"
        = form.text_area :audit_comment, :class => 'tiny elastic'
    %ol.buttons
      %li= form.submit "Add", :disable_with => "Please wait..."

app/views/ingredient_prices/create.js.erb
<% if @price.errors.present? %>
  $('#add_price_form').html("<%= escape_javascript render(:partial => 'form') %>");
<% else %>
  window.location = '<%= ingredient_path(@ingredient) %>';
<% end %>