config/routes.rb
Fms::Application.routes.draw do

  root :to => "fragrances#index"
  resource :session, :only => [:new, :create, :destroy]

  resources :fragrances, :except => [:destroy] do
    resources :formulation_versions, :except => [:destroy], :path => 'versions', :shallow => true do
      put 'publish', :on => :member
    end
  end

  resources :accords, :except => [:destroy] do
    member do
      put :publish
    end
    resources :formulation_versions, :except => [:destroy], :path => 'versions'
    collection do
      get 'autocomplete'
    end
    resources :versions, :except => [:destroy], :controller => 'formulation_versions'
  end

  resources :ingredients do
    collection do
      get 'autocomplete'
    end
    resources :ingredient_prices, :only => [:create]
  end
  resources :ingredient_price_lists, :only => [:create, :update, :index]

end

app/models/accord.rb
class Accord < Formulation

  has_many :formulation_items, :as => :compound
  after_save :update_dependents, :if => :current_version_id_changed?

  class << self
    def import_from_csv(file)
      CSV.read(file, :headers => true).each do |row|
        params = { :origin_formula_id => row['AccordId'], :name => row['AccordName'], :product_year => (row['DateEntry'].split('-').last.to_i + 2000) }
        create_or_update(params)
      end
    end
  end

  def derivatives
    Formulation.includes(:current_version => [:items]).where(:formulation_versions => { :state => 'published', :formulation_items => { :compound_type => 'Accord', :compound_id => id } })
  end

  def derivative_versions
    FormulationVersion.includes(:items).where(:formulation_items => { :compound_type => 'Accord', :compound_id => id })
  end

  def update_dependents
    update_derivatives
    update_derivative_draft_versions
  end

  private
  def update_derivatives
    derivatives.each do |formulation|
      formulation.bump_version!(self)
    end
  end

  def update_derivative_draft_versions
    derivative_versions.drafts.each do |version|
      version.update_accord!(self)
    end
  end
end

app/controllers/accords_controller.rb
class AccordsController < FormulationsController
  layout 'formulations'

  def index
    @accords = Accord.all.paginate :page => params[:page], :per_page => 20
  end

  def new
    @formulation = Accord.new
    @formulation.versions.build.init
    render "formulations/new"
  end

  def create
    @formulation = current_user.accords.build params[:accord]
    if @formulation.save
      redirect_to @formulation, :flash => { :success => 'Accord created.' }
    else
      render "formulations/new"
    end
  end

  def update
    @formulation = Accord.find params[:id]
    if @formulation.update_attributes params[:accord]
      redirect_to accord_url(@formulation, :version => 'draft'), :flash => { :success => "Accord updated" }
    else
      render "formulations/edit"
    end
  end

  def autocomplete
    render :json => Accord.with_name_or_code(params[:term]).limit(10).collect{|i| { :id => i.id, :value => i.to_s, :price_per_gram => i.price_per_gram.round(2) } }
  end
end

app/views/accords/history.html.haml
- @page_title = "History of #{@accord}"

%ul.buttons
  %li= link_to "&laquo; Current Version".html_safe, @accord, :class => 'primary'

%table.list
  %thead
    %tr
      %th Date
      %th By
      %th Description
  %tbody
    - unless @changes.empty?
      - @changes.group_by{|c| c.created_at.to_i}.each do |i, changes|
        %tr
          - date = changes.first.created_at
          %td{ :rowspan => 1+changes.size, :title => date.to_s(:long) }
            = link_to date.to_s(:short), accord_path(@accord, :as_on => date)
          - changes.each do |change|
            %tr
              %td{ :style => 'border-left:1px solid #eee' }= change.user
              %td
                %strong= display_audit_action change
                = change.auditable.revision_at(change.created_at + 1)
    - else
      %tr
        %td.empty{ :colspan => 3 } History Not Available

app/views/accords/index.html.haml
- @page_title = 'Accords'

- content_for :page_header do
  .search_box
    - form_tag nil, :class => 'todo' do
      = text_field_tag :q, nil, :class => :hint, :title => 'Search by accord name or code'

%ul.buttons
  %li= link_to "+ Create Accord", new_accord_path, :class => 'primary'

= render :partial => 'formulations/list', :locals => { :formulations => @accords }