config/routes.rb
Fms::Application.routes.draw do

  root :to => "fragrances#index"
  resource :session, :only => [:new, :create, :destroy]

  resources :fragrances, :except => [:destroy] do
    resources :formulation_versions, :except => [:destroy], :path => 'versions', :shallow => true do
      put 'publish', :on => :member
    end
  end

  resources :accords, :except => [:destroy] do
    member do
      put :publish
    end
    resources :formulation_versions, :except => [:destroy], :path => 'versions'
    collection do
      get 'autocomplete'
    end
    resources :versions, :except => [:destroy], :controller => 'formulation_versions'
  end

  resources :ingredients do
    collection do
      get 'autocomplete'
    end
    resources :ingredient_prices, :only => [:create]
  end
  resources :ingredient_price_lists, :only => [:create, :update, :index]

end

app/models/formulation_version.rb
class FormulationVersion < ActiveRecord::Base

  acts_as_audited
  has_associated_audits

  STATES = %w(draft published obsolete)

  delegate :code, :owner, :product_year, :origin_formula_id, :to => :formulation

  belongs_to :formulation, :counter_cache => :versions_count
  belongs_to :parent_version, :class_name => 'FormulationVersion'
  has_many :items, :class_name => 'FormulationItem', :dependent => :delete_all
  has_many :constituents, :through => :items

  accepts_nested_attributes_for :items, :reject_if => Proc.new{ |o| %w(compound_id quantity).all?{|f| o[f].blank?} }, :allow_destroy => true

  attr_protected :published_at, :state, :formulation_id

  validates :name, :presence => true
  validates :state, :inclusion => STATES

  default_value_for :state, "draft"

  before_create :generate_version_number
  after_create :make_current_version!, :if => Proc.new { |v| v.formulation.versions.count == 1 }

  default_scope order('formulation_versions.id desc')
  scope :drafts, where(:state => 'draft')
  scope :published, where(:state => 'published')

  def net_weight
    items.current.sum(:quantity)
  end

  def unit_price(opts = {})
    constituents.price(opts).to_f
  end
  memoize :unit_price

  def price_per_gram(opts = {})
    unit_price(opts) / net_weight
  end

  def price_per_kilogram(opts = {})
    price_per_gram(opts) * 1000
  end

  def current?
    formulation.current_version == self
  end

  def init
    3.times{ items.build }
    self
  end

  def draft?
    state == 'draft'
  end

  def published?
    state == 'published'
  end

  def editable?
    draft?
  end

  def publish!
    transaction do
      formulation.versions.published.update_all(:state => 'obsolete')
      self.state = 'published'
      self.published_at = Time.now
      self.audit_comment = "Published" unless self.audit_comment.present?
      save!
      make_current_version!
    end
  end

  def make_current_version!
    formulation.current_version = self
    formulation.save!
  end

  def changes
    (audits + associated_audits).sort_by(&:created_at).reverse
  end

  def to_s
    #version_number
    "#{name} (##{formulation.code} / #{version_number})"
  end

  def update_accord!(accord)
    items.current.accords.where(:compound_id => accord.id).each &:explode!
    self.version_updated_at = Time.now
    self.audit_comment = "Updated Accord - #{accord}"
    save!
  end

  def build_copy
    formulation.versions.build(self.attributes).tap do |copy|
      items.current.each{|i| copy.items.build i.attributes}
      copy.parent_version = self
    end
  end

  private

  def generate_version_number
    self.version_number = "#{Time.now.year}#{Time.now.month.to_s.rjust(2,"0")}-#{formulation.versions_count + 1}"
  end
end

app/controllers/formulation_versions_controller.rb
class FormulationVersionsController < ApplicationController
  layout 'formulations'

  before_filter :load_formulation, :only => [:new, :create, :index]

  def index
    @versions = @formulation.versions
  end

  def new
    original = @formulation.versions.find(params[:version_id])
    @version = original.build_copy
  end

  def create
    @formulation_version = @formulation.versions.build(params[:formulation_version])
    if @formulation_version.save
      redirect_to @formulation_version, :success => 'Formulation saved'
    else
      render :new
    end
  end

  def show
    @formulation_version = FormulationVersion.find params[:id]
    @formulation = @formulation_version.formulation
  end

  def edit
    @formulation_version = FormulationVersion.find params[:id]
    @formulation = @formulation_version.formulation
    unless @formulation_version.editable?
      redirect_to :back, :notice => "This version cannot be modified"
    end
  end

  def update
    @formulation_version = FormulationVersion.find params[:id]
    unless @formulation_version.editable?
      redirect_to :back, :notice => "This version cannot be modified"
    end
    if @formulation_version.update_attributes params[:formulation_version]
      redirect_to @formulation_version, :flash => { :success => "Fragrance updated" }
    else
      @formulation = @formulation_version.formulation
    end

  end

  def publish
    @formulation_version = FormulationVersion.find params[:id]
    @formulation_version.publish!
    redirect_to @formulation_version.formulation, :flash => { :success => "#{@formulation_version} published" }
  end

  private
  def load_formulation
    @formulation = Formulation.find(params[:fragrance_id] || params[:accord_id])
  end
end

app/helpers/formulation_versions_helper.rb
module FormulationVersionsHelper
end

app/views/formulation_versions/_form.html.haml
%fieldset 
  %ol.form
    - if(parent_version = form.object.parent_version).present?
      %li
        = form.label :parent_version_id, "Based on"
        %input{ :type => 'text', :value => parent_version.to_s, :readonly => true }
        = form.hidden_field :parent_version_id
    %li
      = form.label :name
      = form.text_field :name
      = reqd

%fieldset
  %legend Ingredients
  %table.prices_form
    %tfoot
      %tr
        %td
          .add_child= add_nested_fields_for(form, :items, 'items', { :label => '+ Add Item', :partial => 'formulations/item_form', :object => FormulationItem.new })
        %td{ :colspan => 3} Total
        %td
          = ThreadLocal.current_currency
          %input#total_price{ :type => 'text', :class => 'numeric', :readonly => true, :value => form.object.new_record? ? nil : form.object.unit_price.round(2) }
    %tbody#items
      = form.fields_for :items do |item_form|
        = render :partial => 'formulations/item_form', :locals => { :form => item_form }

%fieldset 
  %ol.form
    %li
      = form.label :top_note
      = form.text_area :top_note, { :class => 'elastic', :style => 'width: 495px!important;height: 40px;' }
    %li
      = form.label :middle_note
      = form.text_area :middle_note, { :class => 'elastic', :style => 'width: 495px!important;height: 40px;' }
    %li
      = form.label :base_note
      = form.text_area :base_note, { :class => 'elastic', :style => 'width: 495px!important;height: 40px;' }

- content_for :tail do
  :javascript
    $(function() {
      $("body").delegate(".compound_type", 'change', function() {
        $(this).parents('.prices_form').find('.compound').val('').focus();
      });
      $("body").delegate(".compound", 'focus', function() {
        var url = $(this).parents('.prices_form').find('.compound_type').val() == 'Ingredient' ? '#{autocomplete_ingredients_path}' : '#{autocomplete_accords_path}';
        $(this).autocomplete({
          source: url,
          minLength: 2,
          select: function( event, ui ) {
            $(this).next('.compound_id').val(ui.item.id);
            $(this).parents('.item').find('input.price_per_gram').val(ui.item.price_per_gram);
            $(this).parents('.item').find('span.price_per_gram').html(ui.item.price_per_gram);
            calculatePrice($(this).parents('.item'));
          }
        });
      });

      $('.quantity').live('change', function() {
        calculatePrice($(this).parents('.item'));
      });
      $('#items .item').each(function() {
        calculatePrice($(this));
      });
      setInterval("calculateTotalPrice()", 1000);
    });
    function calculatePrice(node) {
      var price_per_gram = node.find('.price_per_gram').val();
      var quantity = node.find('.quantity').val();
      node.find(".price").val(Math.round(price_per_gram * quantity * 100) / 100);
    }
    function calculateTotalPrice() {
      var sum = 0;
      $('#items .item:not(.removed) .price').each(function() {
        var val = parseFloat($(this).val());
        if(!isNaN(val)) sum += parseFloat($(this).val());
      });
      $('#total_price').val(Math.round(sum * 100) / 100);
    }

app/views/formulation_versions/_header.html.haml
%table.form
  %tr
    %th Owner
    %td= formulation_version.owner
    %th Version
    %td
      = formulation_version.version_number
      - if formulation_version.current?
        (current)
      - elsif formulation_version.draft?
  %tr
    %th State
    %td= formulation_version.state
    %th== #{formulation_version.published? ? 'Published' : 'Created'} on
    %td= (formulation_version.published? ? formulation_version.published_at : formulation_version.created_at).to_s(:long)
  %tr
    %th Price
    %td.loud
      == #{number_to_currency(formulation_version.price_per_kilogram, :unit => current_currency.symbol)}
      %span.tip per kg
    %th Net Weight
    %td
      == #{number_with_precision formulation_version.net_weight, :precision => 3}
      %span.tip grams
  %tr
    %th
    %td{ :colspan => 3}
      %a.more.toggle{ :href => '#details' } more

%table#details.form.hidden
  %tr
    %th Product Year
    %td= formulation_version.product_year
    %th Origin Formula ID
    %td= formulation_version.origin_formula_id || "N/A"
  %tr
    %th Top Note
    %td{ :colspan => 3 }= formulation_version.top_note.present? ? formulation_version.top_note : "N/A"
  %tr
    %th Middle Note
    %td{ :colspan => 3 }= formulation_version.middle_note.present? ? formulation_version.middle_note : "N/A"
  %tr
    %th Base Note
    %td{ :colspan => 3 }= formulation_version.base_note.present? ? formulation_version.base_note : "N/A"

app/views/formulation_versions/_items.html.haml
%h3 Ingredients

%table.list.striped
  %thead
    %tr
      %th{ :style => 'width: 70%'} Compound
      %th{ :style => 'text-align: center;', :colspan => 2 } Quantity (grams)
      %th{ :style => 'text-align: center;', :colspan => 2 }== Price
  %tbody
    - formulation_version.items.current.each do |item|
      %tr
        %td= link_to item.compound, item.compound
        %td.numeric
          = number_with_precision item.quantity, :precision => 3
        %td.numeric.quiet
          == #{number_to_percentage item.quantity_percentage, :precision => 2}
        %td.numeric
          = number_to_currency item.price, :unit => current_currency[:symbol]
        %td.numeric.quiet
          == #{number_to_percentage item.price_percentage, :precision => 2}

app/views/formulation_versions/edit.html.haml
- @page_title = "Edit: #{@formulation_version}"

= form_for @formulation_version do |form|
  = form.error_messages
  = render form

  %fieldset
    %ol.buttons
      %li= form.submit "Save", :class => :primary
      %li= cancel_link(@formulation_version)

app/views/formulation_versions/index.html.haml
- @page_title = "#{@formulation.type}: #{@formulation}"

%ul.buttons
  %li
    = link_to "&laquo; Current version".html_safe, @formulation, :class => 'primary'

%h3 Versions
.tip Current version is highlighted

%table.list
  %thead
    %tr
      %th Version
      %th State
      %th Date
      %th By
      %th{ :colspan => 2 } Changes
  %tbody
    - @versions.each do |version|
      %tr{ :class => version.current? ? 'highlight' : nil }
        - rowspan = version.changes.count + 1
        %td{ :rowspan => rowspan }
          = link_to version, version
        %td{ :rowspan => rowspan }= version.state
        - version.changes.each do |change|
          %tr{ :class => version.current? ? 'highlight' : nil }
            %td{ :style => 'width: 50px;border-left: 1px solid #eee' }= change.created_at.to_s(:short)
            %td= change.user
            - unless change.comment.present?
              %td{ :style => 'width: 30px' }= display_audit_action change
              %td
                - if change.auditable.is_a?(FormulationItem)
                  = change.auditable.revision_at(change.created_at + 1)
                - elsif change.action != 'create'
                  = change.audited_changes.keys.collect(&:humanize).join(", ")
                - elsif change.action == 'create' && version.parent_version.present?
                  == based on #{link_to version.parent_version, version.parent_version}
            - else
              %td{ :colspan => 2}
                = change.comment

app/views/formulation_versions/new.html.haml
- @page_title = "New Version of #{@formulation}"

= form_for [@formulation, @version] do |form|
  = form.error_messages
  = render form

  %fieldset
    %ol.buttons
      %li= form.submit "Save", :class => :primary
      %li= cancel_link(@formulation)

app/views/formulation_versions/show.html.haml
- @page_title = @formulation

- if !@formulation_version.current?
  .notice== You aren't viewing the current version of this formulation. Switch to the #{link_to('current version', @formulation)}

= render 'shared/price_preferences_form'
%ul.buttons
  - if @formulation_version.draft?
    %li= link_to "Edit", [:edit, @formulation_version], :class => "primary #{'disabled' if @formulation_version.published?}"
    %li= link_to "Publish", [:publish, @formulation_version], :method => :put, :confirm => 'Really publish this version?'
  %li= link_to "New Version", new_fragrance_formulation_version_path(@formulation, :version_id => @formulation_version.id)
  %li.select
    %a More
    %ul
      %li= link_to "Show All Versions (#{@formulation.versions.count})", [@formulation, :formulation_versions]
      %li= link_to "Copy", new_fragrance_path(:copy_of_id => @formulation_version.id)

= render :partial => 'formulation_versions/header', :locals => { :formulation_version => @formulation_version }
= render :partial => 'formulation_versions/items', :locals => { :formulation_version => @formulation_version }