config/routes.rb
Fms::Application.routes.draw do

  root :to => "fragrances#index"
  resource :session, :only => [:new, :create, :destroy]

  resources :fragrances, :except => [:destroy] do
    resources :formulation_versions, :except => [:destroy], :path => 'versions', :shallow => true do
      put 'publish', :on => :member
    end
  end

  resources :accords, :except => [:destroy] do
    member do
      put :publish
    end
    resources :formulation_versions, :except => [:destroy], :path => 'versions'
    collection do
      get 'autocomplete'
    end
    resources :versions, :except => [:destroy], :controller => 'formulation_versions'
  end

  resources :ingredients do
    collection do
      get 'autocomplete'
    end
    resources :ingredient_prices, :only => [:create]
  end
  resources :ingredient_price_lists, :only => [:create, :update, :index]

end

app/views/layouts/_footer.html.haml
#footer
  .wrapper
    = image_tag "shk_logo.png", :style => "margin-right: 10px;float: left"
    S. H. Kelkar &amp; Co. Pvt. Ltd. 

app/views/layouts/application.html.haml
= inside_layout 'base' do
  - content_for :main_menu do
    #main_menu
      .wrapper
        %ul
          %li{ :class => current_tab?(:formulations) ? 'current' : nil }= link_to 'Formulations', fragrances_path
          %li{ :class => current_tab?(:ingredients) ? 'current' : nil }= link_to 'Ingredients', ingredients_path
          %li{ :class => current_tab?(:admin) ? 'current' : nil }= link_to 'Admin', '#', :class => 'todo'
  = yield

app/views/layouts/base.html.haml
!!!
%html
  %head
    %title= raw [@page_title, Settings.app_name].join(' ~ ')
    = stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'smoothness/jquery-ui-1.8.13.custom', :media => 'screen, projection'
    = csrf_meta_tag
  %body
    #root
      #header
        #top_menu
          .wrapper
            %ul
              - if logged_in?
                %li= current_user
                %li= link_to 'Log out', session_path, :method => :delete
            .logo= Settings.app_name

        = yield :main_menu
        #sub_menu
          .wrapper
            = yield :sub_menu
      #middle
        .wrapper
          = render 'shared/flash_message'
          #main
            #page_header
              = yield :page_header
              %h1= @page_title
            = yield
      #root_footer
    = render 'layouts/footer'
    = javascript_include_tag :defaults
    = javascript_include_tag 'jquery.hint', 'jquery.elastic.source', 'jquery.fitted'
    = yield :tail

app/views/layouts/box.html.haml
!!!
%html
  %head
    %title= [@page_title, Settings.app_name].compact.join(" - ")
    = stylesheet_link_tag 'compiled/box.css', :media => 'screen, projection'
    = csrf_meta_tag
    %noscript
      %meta{ "http-equiv" => 'refresh', "content" => '0; URL=/enable_js'}
  %body
    #box
      .app_name
        = Settings.app_name
      %h1= @page_title
      = render 'shared/flash_message'
      = yield
  = render 'layouts/footer'

app/views/layouts/formulations.html.haml
- @tab = 'formulations'
= inside_layout 'application' do
  - content_for :sub_menu do
    %ul
      %li{:class => controller_name == 'fragrances' ? 'current' : nil}= link_to_unless_current 'Fragrances', fragrances_path
      %li{:class => controller_name == 'accords' ? 'current' : nil}= link_to_unless_current 'Accords', accords_path

  = yield

app/views/layouts/ingredients.html.haml
- @tab = 'ingredients'
= inside_layout 'application' do
  - content_for :sub_menu do
    %ul
      %li{:class => controller_name == 'ingredients' ? 'current' : nil}= link_to_unless_current 'All Ingredients', ingredients_path
      %li{:class => controller_name == 'ingredient_price_lists' ? 'current' : nil}= link_to_unless_current 'Price Lists', ingredient_price_lists_path

  = yield

app/views/layouts/sessions.html.haml
= inside_layout 'box' do
  = yield